<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ChugokuDemoSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');

        $this->db->disableForeignKeyChecks();
        foreach (['inquiries', 'news_articles', 'network_points', 'project_records', 'products', 'product_categories'] as $table) {
            if ($this->db->tableExists($table)) {
                $this->db->table($table)->truncate();
            }
        }
        $this->db->enableForeignKeyChecks();

        $this->db->table('product_categories')->insertBatch([
            [
                'id' => 1,
                'slug' => 'industrial-coatings',
                'title_en' => 'Industrial Coatings',
                'title_id' => 'Coating Industri',
                'description_en' => 'High performance coatings for industrial facilities and steel structures.',
                'description_id' => 'Coating performa tinggi untuk fasilitas industri dan struktur baja.',
                'sort_order' => 1,
                'status' => 'published',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'slug' => 'marine-coatings',
                'title_en' => 'Marine Coatings',
                'title_id' => 'Coating Marine',
                'description_en' => 'Marine paint solutions for vessels, offshore assets, and seawater corrosion protection.',
                'description_id' => 'Solusi cat kapal untuk vessel, aset offshore, dan proteksi korosi air laut.',
                'sort_order' => 2,
                'status' => 'published',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'slug' => 'protective-coatings',
                'title_en' => 'Protective Coatings',
                'title_id' => 'Coating Proteksi',
                'description_en' => 'Long-term corrosion protection for infrastructure, tanks, and pipelines.',
                'description_id' => 'Perlindungan korosi jangka panjang untuk infrastruktur, tank, dan pipa.',
                'sort_order' => 3,
                'status' => 'published',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'slug' => 'flooring-systems',
                'title_en' => 'Flooring Systems',
                'title_id' => 'Sistem Lantai',
                'description_en' => 'Industrial flooring systems with clean, durable, and high performance finish.',
                'description_id' => 'Sistem lantai industri dengan tampilan bersih, durable, dan performa tinggi.',
                'sort_order' => 4,
                'status' => 'published',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        $this->db->table('products')->insertBatch([
            [
                'category_id' => 1,
                'slug' => 'industrial-coatings',
                'title_en' => 'Industrial Coatings',
                'title_id' => 'Coating Industri',
                'excerpt_en' => 'Protecting steel structures and industrial equipment.',
                'excerpt_id' => 'Perlindungan struktur baja dan peralatan industri.',
                'description_en' => 'High performance industrial coatings for plants, steel structures, tanks, and operational assets.',
                'description_id' => 'Coating industri performa tinggi untuk plant, struktur baja, tank, dan aset operasional.',
                'image' => 'product-industrial.jpg',
                'brochure_file' => null,
                'sort_order' => 1,
                'status' => 'published',
                'meta_title_en' => 'Industrial Coatings | Chugoku Paints Indonesia',
                'meta_title_id' => 'Coating Industri | Chugoku Paints Indonesia',
                'meta_description_en' => 'Industrial coating solutions for steel structures and industrial assets.',
                'meta_description_id' => 'Solusi coating industri untuk struktur baja dan aset industri.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 2,
                'slug' => 'marine-coatings',
                'title_en' => 'Marine Coatings',
                'title_id' => 'Coating Marine',
                'excerpt_en' => 'Superior protection for marine and offshore applications.',
                'excerpt_id' => 'Perlindungan unggul untuk aplikasi kapal dan offshore.',
                'description_en' => 'Marine paint systems for vessels, docks, offshore platforms, and seawater corrosion protection.',
                'description_id' => 'Sistem cat kapal untuk vessel, dock, offshore platform, dan proteksi korosi air laut.',
                'image' => 'product-marine.jpg',
                'brochure_file' => null,
                'sort_order' => 2,
                'status' => 'published',
                'meta_title_en' => 'Marine Coatings | Chugoku Paints Indonesia',
                'meta_title_id' => 'Coating Marine | Chugoku Paints Indonesia',
                'meta_description_en' => 'Marine coating solutions for vessels and offshore environments.',
                'meta_description_id' => 'Solusi coating marine untuk kapal dan lingkungan offshore.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 3,
                'slug' => 'protective-coatings',
                'title_en' => 'Protective Coatings',
                'title_id' => 'Coating Proteksi',
                'excerpt_en' => 'Long-term corrosion protection for harsh environments.',
                'excerpt_id' => 'Perlindungan korosi jangka panjang untuk lingkungan ekstrem.',
                'description_en' => 'Protective coating systems for infrastructure, pipelines, tanks, concrete, and heavy duty environments.',
                'description_id' => 'Sistem coating proteksi untuk infrastruktur, pipa, tank, beton, dan lingkungan heavy duty.',
                'image' => 'product-protective.jpg',
                'brochure_file' => null,
                'sort_order' => 3,
                'status' => 'published',
                'meta_title_en' => 'Protective Coatings | Chugoku Paints Indonesia',
                'meta_title_id' => 'Coating Proteksi | Chugoku Paints Indonesia',
                'meta_description_en' => 'Protective coating for corrosion protection and heavy duty applications.',
                'meta_description_id' => 'Coating proteksi untuk perlindungan korosi dan aplikasi heavy duty.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 4,
                'slug' => 'flooring-systems',
                'title_en' => 'Flooring Systems',
                'title_id' => 'Sistem Lantai',
                'excerpt_en' => 'High performance flooring for industrial facilities.',
                'excerpt_id' => 'Flooring performa tinggi untuk fasilitas industri.',
                'description_en' => 'Industrial floor coating systems for factories, warehouses, clean areas, and production facilities.',
                'description_id' => 'Sistem floor coating industri untuk pabrik, gudang, area bersih, dan fasilitas produksi.',
                'image' => 'product-flooring.jpg',
                'brochure_file' => null,
                'sort_order' => 4,
                'status' => 'published',
                'meta_title_en' => 'Flooring Systems | Chugoku Paints Indonesia',
                'meta_title_id' => 'Sistem Lantai | Chugoku Paints Indonesia',
                'meta_description_en' => 'Industrial flooring systems for factories and production facilities.',
                'meta_description_id' => 'Sistem lantai industri untuk pabrik dan fasilitas produksi.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        $this->db->table('project_records')->insertBatch([
            [
                'slug' => 'akashi-kaikyo-bridge',
                'title_en' => 'Akashi Kaikyo Bridge',
                'title_id' => 'Akashi Kaikyo Bridge',
                'location' => 'Japan',
                'application_type' => 'Infrastructure Coating',
                'client_name' => null,
                'project_year' => null,
                'description_en' => 'Infrastructure coating reference for demanding bridge environment.',
                'description_id' => 'Referensi coating infrastruktur untuk lingkungan jembatan yang menantang.',
                'image' => 'project-bridge.jpg',
                'sort_order' => 1,
                'status' => 'published',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'offshore-platform',
                'title_en' => 'Offshore Platform',
                'title_id' => 'Offshore Platform',
                'location' => 'Malaysia',
                'application_type' => 'Marine / Offshore',
                'client_name' => null,
                'project_year' => null,
                'description_en' => 'Marine and offshore coating reference for severe seawater exposure.',
                'description_id' => 'Referensi coating marine dan offshore untuk paparan air laut berat.',
                'image' => 'project-offshore.jpg',
                'sort_order' => 2,
                'status' => 'published',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'power-plant-project',
                'title_en' => 'Power Plant Project',
                'title_id' => 'Proyek Power Plant',
                'location' => 'Thailand',
                'application_type' => 'Protective Coating',
                'client_name' => null,
                'project_year' => null,
                'description_en' => 'Protective coating reference for power plant and industrial assets.',
                'description_id' => 'Referensi coating proteksi untuk power plant dan aset industri.',
                'image' => 'project-power.jpg',
                'sort_order' => 3,
                'status' => 'published',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        $this->db->table('network_points')->insertBatch([
            [
                'name' => 'Jakarta Office',
                'type' => 'office',
                'city' => 'Jakarta',
                'province' => 'DKI Jakarta',
                'address' => 'Jakarta, Indonesia',
                'latitude' => -6.2000000,
                'longitude' => 106.8166660,
                'description_en' => 'Corporate communication, product inquiry, customer relation, and administration support.',
                'description_id' => 'Dukungan komunikasi perusahaan, inquiry produk, customer relation, dan administrasi.',
                'sort_order' => 1,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Industrial Area Coverage',
                'type' => 'coverage',
                'city' => 'Indonesia',
                'province' => 'Indonesia',
                'address' => 'Indonesia',
                'latitude' => -2.5489260,
                'longitude' => 118.0148630,
                'description_en' => 'Support for manufacturing, infrastructure, marine, tank, pipe, and flooring coating applications.',
                'description_id' => 'Dukungan untuk manufaktur, infrastruktur, marine, tank, pipe, dan flooring coating.',
                'sort_order' => 2,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        $this->db->table('news_articles')->insertBatch([
            [
                'slug' => 'new-high-performance-marine-coating',
                'title_en' => 'Chugoku Paints Launches New High Performance Marine Coating',
                'title_id' => 'Chugoku Paints Meluncurkan Marine Coating Performa Tinggi',
                'excerpt_en' => 'Latest product update for marine coating solutions.',
                'excerpt_id' => 'Update produk terbaru untuk solusi marine coating.',
                'content_en' => 'News content can be managed from CMS.',
                'content_id' => 'Konten berita dapat dikelola dari CMS.',
                'image' => 'news-1.jpg',
                'published_at' => $now,
                'status' => 'published',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'sustainable-infrastructure-development',
                'title_en' => 'Supporting Sustainable Infrastructure Development',
                'title_id' => 'Mendukung Pengembangan Infrastruktur Berkelanjutan',
                'excerpt_en' => 'Corporate update about infrastructure and sustainability.',
                'excerpt_id' => 'Update corporate tentang infrastruktur dan keberlanjutan.',
                'content_en' => 'News content can be managed from CMS.',
                'content_id' => 'Konten berita dapat dikelola dari CMS.',
                'image' => 'news-2.jpg',
                'published_at' => $now,
                'status' => 'published',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        $this->db->table('inquiries')->insertBatch([
            [
                'name' => 'PT Marine Sample',
                'company' => 'PT Marine Sample',
                'email' => 'contact@example.com',
                'phone' => '+62 21 1234 5678',
                'interest' => 'Marine Coatings',
                'message' => 'We need information about marine coating products.',
                'status' => 'new',
                'admin_note' => null,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'Demo Seeder',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
